[package]
name = "moraebox-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
fs2.workspace = true
moraebox-box = { path = "../moraebox-box", version = "0.1.0" }
moraebox-core = { path = "../moraebox-core", version = "0.1.0" }
serde.workspace = true
thiserror.workspace = true
tempfile.workspace = true
tokio.workspace = true
rustix = { workspace = true, features = ["termios"] }

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
