[package]
name = "moraebox-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "morae"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["env"] }
clap_complete.workspace = true
moraebox-box = { path = "../moraebox-box" }
moraebox-core = { path = "../moraebox-core" }
moraebox-image = { path = "../moraebox-image" }
moraebox-runtime = { path = "../moraebox-runtime" }
moraebox-sdk = { path = "../moraebox-sdk" }
humantime.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
base64.workspace = true
tempfile.workspace = true

[lints]
workspace = true
