[package]
name = "moraebox-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "morae"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["env"] }
clap_complete.workspace = true
futures-util.workspace = true
moraebox-box = { path = "../moraebox-box", version = "0.1.0" }
moraebox-core = { path = "../moraebox-core", version = "0.1.0" }
moraebox-image = { path = "../moraebox-image", version = "0.1.0" }
moraebox-runtime = { path = "../moraebox-runtime", version = "0.1.0" }
moraebox-sdk = { path = "../moraebox-sdk", version = "0.1.0" }
humantime.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
toml.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true
rustix = { workspace = true, features = ["termios"] }

[dev-dependencies]
base64.workspace = true
tempfile.workspace = true

[lints]
workspace = true
