[package]
name = "moraebox-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
moraebox-box = { path = "../moraebox-box", version = "0.1.0" }
moraebox-core = { path = "../moraebox-core", version = "0.1.0" }
moraebox-image = { path = "../moraebox-image", version = "0.1.0" }
moraebox-runtime = { path = "../moraebox-runtime", version = "0.1.0" }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true

[lints]
workspace = true
