[package]
name = "moraebox-vmm-helper"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[[bin]]
name = "morae-vmm-helper"
path = "src/main.rs"

[dependencies]
clap.workspace = true
libloading.workspace = true
moraebox-protocol = { path = "../moraebox-protocol", version = "0.1.0" }
tempfile.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[lints]
workspace = true
